name: 'Continuous Delivery'

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  test-and-deploy-to-staging:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Set Credential File
      run: |
        echo '${{ secrets.STAGING_CREDENTIALS }}' > gcp_test_credentials.json
      env:
        GOOGLE_APPLICATION_CREDENTIALS: gcp_test_credentials.json
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests with pytest
      run: python3 -m pytest

    - name: Gcp Auth
      uses: 'google-github-actions/auth@v1'
      with: 
        credentials_json: '${{ secrets.STAGING_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud To Deploy Staging'
      run: 'gcloud app deploy --quiet'